In [1]:
#matrix multiplication and transpose
import numpy as np
from scipy import linalg
a=np.arange(1,7)
b=np.arange(2,8)
x=a.reshape(2,3)
y=b.reshape(3,2)
print("First Matrix \n",x,"\nSecond matrix \n",y)
print("Product Matrix\n",np.dot(x,y))
print("Transpose of First matrix\n",np.transpose(x))

First Matrix 
 [[1 2 3]
 [4 5 6]] 
Second matrix 
 [[2 3]
 [4 5]
 [6 7]]
Product Matrix
 [[28 34]
 [64 79]]
Transpose of First matrix
 [[1 4]
 [2 5]
 [3 6]]
